dictionaries = [
    "de",
    "en_us",
]
words = [
    "CLI",
    "Gmb",
    "angebot",
    "anthropics",
    "anton",
    "aufzählungspunkte",
    "barrierefreiheit",
    "bcc",
    "bebas",
    "bezier",
    "bidi",
    "blogautor",
    "blogpost",
    "blogposts",
    "breakpoint",
    "bunx",
    "bzw",
    "cheerleading",
    "claude",
    "cleverreach",
    "clsx",
    "codespaces",
    "commitizen",
    "commitlint",
    "cta",
    "cursorrules",
    "cva",
    "czg",
    "dinter",
    "doi",
    "dosb",
    "dotenv",
    "dropzone",
    "duplicatable",
    "engerser",
    "esm",
    "evenodd",
    "facebook",
    "figcaption",
    "finanzen",
    "firefox",
    "fontsource",
    "geist",
    "github",
    "gotenstraße",
    "groq",
    "hotspot",
    "impressum",
    "inlines",
    "instagram",
    "irlich",
    "j4rxwl5m",
    "jako",
    "keyof",
    "kommentarfeld",
    "kontakt",
    "kurse",
    "lockb",
    "logomark",
    "loopitem",
    "ltr",
    "lucide",
    "marschke",
    "maxage",
    "mheob",
    "minmax",
    "mitgliedschaft",
    "neuwied",
    "nextjs",
    "nodenext",
    "noopener",
    "noreferrer",
    "nosonar",
    "noto",
    "nowrap",
    "nums",
    "nvmrc",
    "oklch",
    "oneline",
    "openai",
    "opengraph",
    "openssl",
    "oxc",
    "oxfmt",
    "oxlint",
    "pagebuilder",
    "pappelstadion",
    "perma",
    "portabletext",
    "porträtbild",
    "pragent",
    "preact",
    "qube",
    "renderable",
    "revalidated",
    "rgba",
    "safelink",
    "screenreader",
    "seite",
    "seitfallzieher",
    "shadcn",
    "shadcn's",
    "shitposting",
    "showtanz",
    "slugification",
    "slugified",
    "sonarcloud",
    "sonarlint",
    "sonarqube",
    "srcset",
    "stega",
    "subcomponents",
    "taekwondo",
    "tailwindcss",
    "taskfile",
    "taze",
    "textonly",
    "theming",
    "treeify",
    "tsg",
    "tsgi",
    "typegen",
    "typeof",
    "vaul",
    "vercel",
    "verein",
    "verwaltung",
    "wcag",
    "webp",
    "whatsapp",
    "xlarge",
    "youtube",
    "zod",
    "zoomable",
]
