dictionaries = ["de", "en_us"]
words = [
	"angebot",
	"anthropics",
	"anton",
	"aufzählungspunkte",
	"barrierefreiheit",
	"bebas",
	"bezier",
	"blogautor",
	"blogpost",
	"blogposts",
	"cheerleading",
	"claude",
	"cleverreach",
	"codespaces",
	"commitizen",
	"commitlint",
	"cursorrules",
	"cva",
	"czg",
	"dinter",
	"dosb",
	"dotenv",
	"engerser",
	"evenodd",
	"facebook",
	"figcaption",
	"finanzen",
	"firefox",
	"fontsource",
	"geist",
	"github",
	"gotenstraße",
	"groq",
	"hotspot",
	"impressum",
	"instagram",
	"irlich",
	"j4rxwl5m",
	"jako",
	"keyof",
	"kontakt",
	"kurse",
	"lockb",
	"logomark",
	"lucide",
	"marschke",
	"mheob",
	"mitgliedschaft",
	"nodenext",
	"noopener",
	"noreferrer",
	"nosonar",
	"noto",
	"nowrap",
	"nums",
	"nvmrc",
	"oklch",
	"oneline",
	"openai",
	"opengraph",
	"openssl",
	"oxfmt",
	"oxlint",
	"pagebuilder",
	"pappelstadion",
	"portabletext",
	"porträtbild",
	"pragent",
	"preact",
	"qube",
	"rgba",
	"screenreader",
	"seite",
	"seitfallzieher",
	"shadcn",
	"shadcn's",
	"shitposting",
	"showtanz",
	"slugification",
	"slugified",
	"sonarcloud",
	"sonarlint",
	"sonarqube",
	"srcset",
	"stega",
	"subcomponents",
	"taekwondo",
	"tailwindcss",
	"taskfile",
	"taze",
	"theming",
	"treeify",
	"tsgi",
	"typegen",
	"typeof",
	"vaul",
	"vercel",
	"verein",
	"verwaltung",
	"wcag",
	"webp",
	"whatsapp",
	"xlarge",
	"youtube",
	"zod",
	"zoomable",
]
