packages:
  - apps/*
  - packages/*
catalog:
  "@types/node": ^22.13.4
  "@types/react": ^19.0.8
  "@types/react-dom": ^19.0.3
  eslint: ^9.20.1
  react: ^19.0.0
  react-dom: ^19.0.0
  sanity: ^3.75.0
  typescript: ^5.7.3
