packages:
  - apps/*
  - packages/*
catalog:
  "@types/node": ^22.10.10
  "@types/react": ^19.0.8
  "@types/react-dom": ^19.0.3
  eslint: 9.14.0
  react: ^19.0.0
  react-dom: ^19.0.0
  sanity: ^3.71.2
  typescript: ^5.7.3
