packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - scrollmirror
  - sharp
  - unrs-resolver
catalogMode: prefer

catalog:
  "@antfu/ni": ^27.0.0
  "@commitlint/cli": ^20.1.0
  "@cspell/dict-de-de": ^4.1.2
  "@eslint-react/eslint-plugin": ^2.2.3
  "@hookform/resolvers": ^5.2.2
  "@icons-pack/react-simple-icons": ^13.8.0
  "@mheob/commitlint-config": ^1.2.5
  "@mheob/eslint-config": ^8.14.5
  "@mheob/prettier-config": ^3.3.4
  "@mheob/tsconfig": ^2.2.1
  "@next/eslint-plugin-next": ^16.0.0
  "@radix-ui/react-dialog": 1.1.15
  "@radix-ui/react-icons": ^1.3.2
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-navigation-menu": ^1.2.14
  "@radix-ui/react-select": ^2.2.6
  "@radix-ui/react-separator": ^1.1.7
  "@radix-ui/react-slot": ^1.2.3
  "@sanity/assist": ^5.0.1
  "@sanity/client": ^7.12.0
  "@sanity/icons": ^3.7.4
  "@sanity/image-url": ^1.2.0
  "@sanity/locale-de-de": ^1.1.26
  "@sanity/ui": ^3.1.11
  "@sanity/vision": ^4.11.0
  "@tailwindcss/postcss": ^4.1.16
  "@tailwindcss/typography": ^0.5.19
  "@types/node": ^22.18.12
  "@types/react": ^19.2.2
  "@types/react-dom": ^19.2.2
  "@vercel/analytics": ^1.5.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commitizen: ^4.3.1
  cspell: ^9.2.2
  cz-git: ^1.12.0
  dotenv: ^17.2.3
  eslint: ^9.38.0
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  husky: ^9.1.7
  lint-staged: ^16.2.6
  lucide-react: ^0.548.0
  next: ^16.0.0
  next-sanity: ^11.6.2
  postcss: ^8.5.6
  postcss-load-config: ^6.0.1
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.7.1
  react: ^19.2.0
  react-dom: ^19.2.0
  react-hook-form: ^7.65.0
  react-icons: ^5.5.0
  sanity: ^4.11.0
  sanity-plugin-media: ^4.0.0
  server-only: ^0.0.1
  slugify: ^1.6.6
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.16
  tailwindcss-animate: ^1.0.7
  taze: ^19.8.1
  turbo: ^2.5.8
  typescript: ^5.9.3
  vaul: ^1.1.2
  zod: ^4.1.12
