packages:
  - apps/*
  - packages/*
catalog:
  "@types/node": ^22.13.1
  "@types/react": ^19.0.8
  "@types/react-dom": ^19.0.3
  eslint: ^9.20.0
  react: ^19.0.0
  react-dom: ^19.0.0
  sanity: ^3.74.1
  typescript: ^5.7.3
