packages:
  - apps/*
  - packages/*
catalog:
  "@types/node": ^22.13.10
  "@types/react": ^19.0.11
  "@types/react-dom": ^19.0.4
  eslint: ^9.22.0
  react: ^19.0.0
  react-dom: ^19.0.0
  sanity: ^3.80.1
  typescript: ^5.8.2
