packages:
  - apps/*
  - packages/*
catalog:
  "@types/node": ^22.15.2
  "@types/react": ^19.1.2
  "@types/react-dom": ^19.1.2
  eslint: ^9.25.1
  react: ^19.1.0
  react-dom: ^19.1.0
  sanity: ^3.86.1
  typescript: ^5.8.3
