packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - scrollmirror
  - sharp
  - unrs-resolver

catalogMode: prefer

catalog:
  "@antfu/ni": ^26.0.1
  "@commitlint/cli": ^20.0.0
  "@cspell/dict-de-de": ^4.1.2
  "@eslint-react/eslint-plugin": ^1.53.1
  "@hookform/resolvers": ^5.2.2
  "@icons-pack/react-simple-icons": ^13.7.0
  "@mheob/commitlint-config": ^1.2.4
  "@mheob/eslint-config": ^8.13.0
  "@mheob/prettier-config": ^3.3.4
  "@mheob/tsconfig": ^2.2.1
  "@next/eslint-plugin-next": ^15.5.4
  "@radix-ui/react-dialog": ^1.1.15
  "@radix-ui/react-icons": ^1.3.2
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-navigation-menu": ^1.2.14
  "@radix-ui/react-select": ^2.2.6
  "@radix-ui/react-separator": ^1.1.7
  "@radix-ui/react-slot": ^1.2.3
  "@sanity/assist": ^5.0.0
  "@sanity/client": ^7.11.2
  "@sanity/image-url": ^1.2.0
  "@sanity/locale-de-de": ^1.1.26
  "@sanity/ui": ^3.1.7
  "@sanity/vision": ^4.10.1
  "@tailwindcss/postcss": ^4.1.13
  "@tailwindcss/typography": ^0.5.19
  "@types/node": ^22.18.6
  "@types/react": ^19.1.13
  "@types/react-dom": ^19.1.9
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commitizen: ^4.3.1
  cspell: ^9.2.1
  cz-git: ^1.12.0
  dotenv: ^17.2.2
  eslint: ^9.36.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.22
  husky: ^9.1.7
  lint-staged: ^16.2.1
  lucide-react: ^0.544.0
  next: ^15.5.4
  next-sanity: ^11.4.2
  postcss: ^8.5.6
  postcss-load-config: ^6.0.1
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  react: ^19.1.1
  react-dom: ^19.1.1
  react-hook-form: ^7.63.0
  react-icons: ^5.5.0
  sanity: ^4.10.1
  sanity-plugin-media: ^4.0.0
  server-only: ^0.0.1
  slugify: ^1.6.6
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.13
  tailwindcss-animate: ^1.0.7
  taze: ^19.7.0
  turbo: ^2.5.8
  typescript: ^5.9.2
  vaul: ^1.1.2
  zod: ^4.1.11
