packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - scrollmirror
  - sharp
  - unrs-resolver
catalogMode: prefer
catalog:
  "@antfu/ni": ^25.0.0
  "@commitlint/cli": ^19.8.1
  "@cspell/dict-de-de": ^4.1.0
  "@eslint-react/eslint-plugin": ^1.52.2
  "@hookform/resolvers": ^5.1.1
  "@icons-pack/react-simple-icons": ^13.1.0
  "@mheob/commitlint-config": ^1.2.3
  "@mheob/eslint-config": ^8.11.0
  "@mheob/prettier-config": ^3.3.3
  "@mheob/tsconfig": ^2.2.1
  "@next/eslint-plugin-next": ^15.3.4
  "@radix-ui/react-dialog": ^1.1.14
  "@radix-ui/react-icons": ^1.3.2
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-navigation-menu": ^1.2.13
  "@radix-ui/react-select": ^2.2.5
  "@radix-ui/react-separator": ^1.1.7
  "@radix-ui/react-slot": ^1.2.3
  "@sanity/assist": ^4.3.0
  "@sanity/client": ^7.6.0
  "@sanity/image-url": ^1.1.0
  "@sanity/locale-de-de": ^1.1.22
  "@sanity/ui": ^2.16.2
  "@sanity/vision": ^3.93.0
  "@tailwindcss/postcss": ^4.1.10
  "@tailwindcss/typography": ^0.5.16
  "@types/node": ^22.15.32
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commitizen: ^4.3.1
  cspell: ^9.1.1
  cz-git: ^1.11.2
  dotenv: ^16.5.0
  eslint: ^9.29.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  husky: ^9.1.7
  lint-staged: ^16.1.2
  lucide-react: ^0.518.0
  next: ^15.3.4
  next-sanity: ^9.12.0
  postcss: ^8.5.6
  postcss-load-config: ^6.0.1
  prettier: ^3.5.3
  prettier-plugin-tailwindcss: ^0.6.12
  react: ^19.1.0
  react-dom: ^19.1.0
  react-hook-form: ^7.58.1
  react-icons: ^5.5.0
  sanity: ^3.93.0
  sanity-plugin-media: ^3.0.3
  server-only: ^0.0.1
  slugify: ^1.6.6
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.10
  tailwindcss-animate: ^1.0.7
  taze: ^19.1.0
  turbo: ^2.5.4
  typescript: ^5.8.3
  vaul: ^1.1.2
  zod: ^3.25.67
