packages:
  - apps/*
  - packages/*
catalog:
  "@types/react": ^19.0.2
  "@types/react-dom": ^19.0.2
  "@types/node": ^22.10.3
  eslint: 9.14.0
  react: ^19.0.0
  react-dom: ^19.0.0
  sanity: ^3.68.3
  typescript: ^5.7.2
