packages:
  - apps/*
  - packages/*
catalog:
  "@types/node": ^22.15.30
  "@types/react": ^19.1.6
  "@types/react-dom": ^19.1.6
  eslint: ^9.28.0
  react: ^19.1.0
  react-dom: ^19.1.0
  sanity: ^3.91.0
  typescript: ^5.8.3
  zod: ^3.25.56
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - unrs-resolver
