/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type NewsOverviewCategory = {
	_id: string;
	_type: 'newsOverviewCategory';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	content: {
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
			contactPersons: Array<{
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				_key: string;
				[internalGroqTypeReferenceTo]?: 'person';
			}>;
		};
	};
};

export type NewsArticlePage = {
	_id: string;
	_type: 'news-article-page';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	subtitle: string;
};

export type DepartmentsPage = {
	_id: string;
	_type: 'departmentsPage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	slug?: Slug;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	content: {
		departmentsSection: {
			title: string;
			subtitle: string;
			intro?: string;
		};
		stats: Array<
			{
				_key: string;
			} & Stats
		>;
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
			contactPersons: Array<{
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				_key: string;
				[internalGroqTypeReferenceTo]?: 'person';
			}>;
		};
	};
};

export type Spacer = {
	_type: 'spacer';
	variant?: 'default';
};

export type Grid = {
	_type: 'grid';
	title?: string;
	columns: Columns;
	items?: Array<
		| {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt: string;
				description?: string;
				_type: 'mainImage';
				_key: string;
		  }
		| ({
				_key: string;
		  } & BlockContent)
	>;
};

export type Blockquote = {
	_type: 'blockquote';
	quote?: string;
	author?: string;
};

export type TrainingTime = {
	_type: 'trainingTime';
	season: 'yearly' | 'summer' | 'winter';
	weekday: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
	startTime: string;
	endTime: string;
	venue: {
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: 'venue';
	};
	note?: string;
};

export type Stats = {
	_type: 'stats';
	title: string;
	value: number;
	suffix?: string;
};

export type SingleGroupPage = {
	_id: string;
	_type: 'singleGroupPage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	content: {
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
		};
		trainingSection: {
			title: string;
		};
	};
};

export type Privacy = {
	_id: string;
	_type: 'privacy';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	slug?: Slug;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	introText: BlockContent;
	address: string;
	phone?: string;
	email: string;
	content: BlockContent;
};

export type NewsOverview = {
	_id: string;
	_type: 'newsOverview';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	slug?: Slug;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	content: {
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
			contactPersons: Array<{
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				_key: string;
				[internalGroqTypeReferenceTo]?: 'person';
			}>;
		};
	};
};

export type Membership = {
	_id: string;
	_type: 'membership';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	slug?: Slug;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	intro: BlockContent;
	downloadsSection: {
		title: string;
		subtitle: string;
		intro?: string;
		downloads: Array<
			{
				_key: string;
			} & DocumentDownload
		>;
	};
	contactPersonsSection: {
		title: string;
		subtitle: string;
		intro?: string;
		contactPersons: Array<{
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			_key: string;
			[internalGroqTypeReferenceTo]?: 'person';
		}>;
	};
};

export type BlockContent = {
	_type: 'blockContent';
	text?: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: 'span';
			_key: string;
		}>;
		style?: 'normal' | 'h2' | 'h3' | 'blockquote';
		listItem?: 'bullet' | 'number';
		markDefs?: Array<{
			href?: string;
			_type: 'link';
			_key: string;
		}>;
		level?: number;
		_type: 'block';
		_key: string;
	}>;
};

export type Imprint = {
	_id: string;
	_type: 'imprint';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	slug?: Slug;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	intro?: SimpleBlockContent;
	address: SimpleBlockContent;
	registerCourt: string;
	registerNo: string;
	represented: SimpleBlockContent;
	email: string;
	contactForm: InternalLink;
	responsible: string;
	consumerDisputeResolution: string;
	technicalQuestionsName: string;
	technicalQuestionsEmail: string;
	support: SimpleBlockContent;
	credits: SimpleBlockContent;
};

export type InternalLink = {
	_type: 'internalLink';
	title: string;
	link?:
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'news.article';
		  }
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'home';
		  }
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'aboutUs';
		  }
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'contact';
		  }
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'groupsPage';
		  }
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'imprint';
		  }
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'membership';
		  }
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'newsOverview';
		  }
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'privacy';
		  }
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'singleGroupPage';
		  };
};

export type GroupsPage = {
	_id: string;
	_type: 'groupsPage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	content: {
		groupsSection: {
			title: string;
			subtitle: string;
			intro?: string;
		};
		stats: Array<
			{
				_key: string;
			} & Stats
		>;
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
		};
	};
};

export type Contact = {
	_id: string;
	_type: 'contact';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	slug?: Slug;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	content: {
		receiver: Array<
			{
				_key: string;
			} & ContactNameMail
		>;
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
			contactPersons: Array<{
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				_key: string;
				[internalGroqTypeReferenceTo]?: 'person';
			}>;
		};
	};
};

export type AboutUs = {
	_id: string;
	_type: 'aboutUs';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	slug?: Slug;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	content: {
		gallerySection?: {
			title: string;
			subtitle: string;
			intro?: string;
			images: Array<{
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt: string;
				description?: string;
				_type: 'extendedImage';
				_key: string;
			}>;
		};
		chronicleSection?: {
			title: string;
			subtitle: string;
			intro?: string;
			chronicle?: Array<
				{
					_key: string;
				} & ImageCard
			>;
		};
		visionSection: {
			title: string;
			subtitle: string;
			intro?: string;
			cta: string;
		};
		stats: Array<
			{
				_key: string;
			} & Stats
		>;
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
			contactPersons: Array<{
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				_key: string;
				[internalGroqTypeReferenceTo]?: 'person';
			}>;
		};
	};
};

export type Home = {
	_id: string;
	_type: 'home';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	slug?: Slug;
	title: string;
	subtitle: string;
	intro?: string;
	meta?: MetaFields;
	content: {
		featureSection: {
			title: string;
			subtitle: string;
			intro?: string;
			features?: Array<{
				title: string;
				intro: string;
				icon: string;
				_type: 'feature';
				_key: string;
			}>;
		};
		visionSection: {
			title: string;
			subtitle: string;
			intro?: string;
			cta: string;
		};
		groupsSection: {
			title: string;
			subtitle: string;
		};
		stats: Array<
			{
				_key: string;
			} & Stats
		>;
		pricingSection: {
			title: string;
			subtitle: string;
			intro?: string;
			pricingYouth: {
				title: string;
				subtitle: string;
				intro?: string;
				price: number;
				benefitsTitle: string;
				benefits: Array<string>;
				cta: string;
			};
			pricingFamily: {
				title: string;
				subtitle: string;
				intro?: string;
				price: number;
				benefitsTitle: string;
				benefits: Array<string>;
				cta: string;
			};
			pricingAdult: {
				title: string;
				subtitle: string;
				intro?: string;
				price: number;
				benefitsTitle: string;
				benefits: Array<string>;
				cta: string;
			};
		};
		testimonialSection: {
			title: string;
			subtitle: string;
			testimonials?: Array<{
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				_key: string;
				[internalGroqTypeReferenceTo]?: 'testimonial';
			}>;
		};
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
			contactPersons: Array<{
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				_key: string;
				[internalGroqTypeReferenceTo]?: 'person';
			}>;
		};
		newsSection: {
			title: string;
			subtitle: string;
			intro?: string;
		};
	};
};

export type ImageCard = {
	_type: 'imageCard';
	title?: string;
	description?: string;
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
	};
};

export type ExternalLink = {
	_type: 'externalLink';
	title: string;
	url: string;
};

export type DocumentDownload = {
	_type: 'documentDownload';
	title: string;
	document: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
		};
		media?: unknown;
		_type: 'file';
	};
};

export type ContactNameMail = {
	_type: 'contactNameMail';
	name: string;
	email: string;
};

export type Columns = {
	_type: 'columns';
	small?: '1' | '2' | '3' | '4';
	medium?: '1' | '2' | '3' | '4';
	large?: '1' | '2' | '3' | '4';
};

export type SiteSettings = {
	_id: string;
	_type: 'site-settings';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	meta?: MetaFields;
	metadataBase?: string;
	contact?: {
		address: string;
		phone: string;
		email: string;
	};
	newsletter?: {
		title: string;
		cta: string;
	};
	mainNavigation?: Array<
		| ({
				_key: string;
		  } & InternalLink)
		| ({
				_key: string;
		  } & ExternalLink)
	>;
	legalNavigation?: Array<
		{
			_key: string;
		} & InternalLink
	>;
	socialFields?: SocialFields;
};

export type SocialFields = {
	_type: 'socialFields';
	whatsapp?: string;
	facebook?: string;
	instagram?: string;
	youtube?: string;
};

export type Venue = {
	_id: string;
	_type: 'venue';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	description: SimpleBlockContent;
	type: 'hall-1' | 'hall-2' | 'hall-3' | 'cinder' | 'hybrid' | 'artificial-turf' | 'grass';
	mainImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'image';
	};
	location?: {
		name: string;
		street: string;
		houseNumber: string;
		zipCode?: string;
		city: string;
	};
};

export type Testimonial = {
	_id: string;
	_type: 'testimonial';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	firstName: string;
	lastName: string;
	image: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
	};
	role: string;
	quote: string;
	show?: boolean;
};

export type HonoraryMember = {
	_id: string;
	_type: 'honoraryMember';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	firstName: string;
	lastName: string;
	image: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
	};
	memberSince: string;
};

export type Person = {
	_id: string;
	_type: 'person';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	firstName: string;
	lastName: string;
	image: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
	};
	phone?: string;
	contactAs: 'email' | 'phone' | 'whatsapp' | 'both';
	affiliations?: Array<{
		department:
			| 'admin'
			| 'children-gymnastics'
			| 'courses'
			| 'dance'
			| 'other-sports'
			| 'soccer'
			| 'taekwondo';
		team:
			| {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'group.admin';
			  }
			| {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'group.children-gymnastics';
			  }
			| {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'group.courses';
			  }
			| {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'group.dance';
			  }
			| {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'group.other-sports';
			  }
			| {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'group.soccer';
			  }
			| {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'group.taekwondo';
			  };
		role: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'role';
		};
		taskDescription: string;
		sortOrder?: number;
		_type: 'affiliation';
		_key: string;
	}>;
};

export type Role = {
	_id: string;
	_type: 'role';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	email?: string;
};

export type GroupTaekwondo = {
	_id: string;
	_type: 'group.taekwondo';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	email: string;
	overviewTitle?: string;
	sortOrder: number;
	description: SimpleBlockContent;
	icon:
		| 'Badminton'
		| 'Bodenturnen'
		| 'Cheerleading'
		| 'Fitness'
		| 'Fussball'
		| 'Gymnastik'
		| 'Jujutsu'
		| 'Pilates'
		| 'RopeSkipping'
		| 'SportInGebaeuden'
		| 'Sportakrobatik'
		| 'StepAerobic'
		| 'Taekwondo'
		| 'Tanzen'
		| 'Turnen'
		| 'Wandern'
		| 'Yoga';
	featuredImage: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
	};
	images?: Array<{
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
		_key: string;
	}>;
	training: {
		trainingDescription?: SimpleBlockContent;
		trainingTimes?: Array<
			{
				_key: string;
			} & TrainingTime
		>;
	};
	isSportGroup: boolean;
};

export type GroupSoccer = {
	_id: string;
	_type: 'group.soccer';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	email: string;
	overviewTitle?: string;
	sortOrder: number;
	description: SimpleBlockContent;
	icon:
		| 'Badminton'
		| 'Bodenturnen'
		| 'Cheerleading'
		| 'Fitness'
		| 'Fussball'
		| 'Gymnastik'
		| 'Jujutsu'
		| 'Pilates'
		| 'RopeSkipping'
		| 'SportInGebaeuden'
		| 'Sportakrobatik'
		| 'StepAerobic'
		| 'Taekwondo'
		| 'Tanzen'
		| 'Turnen'
		| 'Wandern'
		| 'Yoga';
	featuredImage: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
	};
	images?: Array<{
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
		_key: string;
	}>;
	training: {
		trainingDescription?: SimpleBlockContent;
		trainingTimes?: Array<
			{
				_key: string;
			} & TrainingTime
		>;
	};
	isSportGroup: boolean;
};

export type GroupOtherSports = {
	_id: string;
	_type: 'group.other-sports';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	email: string;
	overviewTitle?: string;
	sortOrder: number;
	description: SimpleBlockContent;
	icon:
		| 'Badminton'
		| 'Bodenturnen'
		| 'Cheerleading'
		| 'Fitness'
		| 'Fussball'
		| 'Gymnastik'
		| 'Jujutsu'
		| 'Pilates'
		| 'RopeSkipping'
		| 'SportInGebaeuden'
		| 'Sportakrobatik'
		| 'StepAerobic'
		| 'Taekwondo'
		| 'Tanzen'
		| 'Turnen'
		| 'Wandern'
		| 'Yoga';
	featuredImage: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
	};
	images?: Array<{
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
		_key: string;
	}>;
	training: {
		trainingDescription?: SimpleBlockContent;
		trainingTimes?: Array<
			{
				_key: string;
			} & TrainingTime
		>;
	};
	isSportGroup: boolean;
};

export type GroupDance = {
	_id: string;
	_type: 'group.dance';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	email: string;
	overviewTitle?: string;
	sortOrder: number;
	description: SimpleBlockContent;
	icon:
		| 'Badminton'
		| 'Bodenturnen'
		| 'Cheerleading'
		| 'Fitness'
		| 'Fussball'
		| 'Gymnastik'
		| 'Jujutsu'
		| 'Pilates'
		| 'RopeSkipping'
		| 'SportInGebaeuden'
		| 'Sportakrobatik'
		| 'StepAerobic'
		| 'Taekwondo'
		| 'Tanzen'
		| 'Turnen'
		| 'Wandern'
		| 'Yoga';
	featuredImage: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
	};
	images?: Array<{
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
		_key: string;
	}>;
	training: {
		trainingDescription?: SimpleBlockContent;
		trainingTimes?: Array<
			{
				_key: string;
			} & TrainingTime
		>;
	};
	isSportGroup: boolean;
};

export type GroupCourses = {
	_id: string;
	_type: 'group.courses';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	email: string;
	overviewTitle?: string;
	sortOrder: number;
	description: SimpleBlockContent;
	icon:
		| 'Badminton'
		| 'Bodenturnen'
		| 'Cheerleading'
		| 'Fitness'
		| 'Fussball'
		| 'Gymnastik'
		| 'Jujutsu'
		| 'Pilates'
		| 'RopeSkipping'
		| 'SportInGebaeuden'
		| 'Sportakrobatik'
		| 'StepAerobic'
		| 'Taekwondo'
		| 'Tanzen'
		| 'Turnen'
		| 'Wandern'
		| 'Yoga';
	featuredImage: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
	};
	images?: Array<{
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
		_key: string;
	}>;
	training: {
		trainingDescription?: SimpleBlockContent;
		trainingTimes?: Array<
			{
				_key: string;
			} & TrainingTime
		>;
	};
	isSportGroup: boolean;
};

export type GroupChildrenGymnastics = {
	_id: string;
	_type: 'group.children-gymnastics';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	email: string;
	overviewTitle?: string;
	sortOrder: number;
	description: SimpleBlockContent;
	icon:
		| 'Badminton'
		| 'Bodenturnen'
		| 'Cheerleading'
		| 'Fitness'
		| 'Fussball'
		| 'Gymnastik'
		| 'Jujutsu'
		| 'Pilates'
		| 'RopeSkipping'
		| 'SportInGebaeuden'
		| 'Sportakrobatik'
		| 'StepAerobic'
		| 'Taekwondo'
		| 'Tanzen'
		| 'Turnen'
		| 'Wandern'
		| 'Yoga';
	featuredImage: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
	};
	images?: Array<{
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
		_key: string;
	}>;
	training: {
		trainingDescription?: SimpleBlockContent;
		trainingTimes?: Array<
			{
				_key: string;
			} & TrainingTime
		>;
	};
	isSportGroup: boolean;
};

export type GroupAdmin = {
	_id: string;
	_type: 'group.admin';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	email: string;
	overviewTitle?: string;
	sortOrder: number;
	description: SimpleBlockContent;
	icon:
		| 'Badminton'
		| 'Bodenturnen'
		| 'Cheerleading'
		| 'Fitness'
		| 'Fussball'
		| 'Gymnastik'
		| 'Jujutsu'
		| 'Pilates'
		| 'RopeSkipping'
		| 'SportInGebaeuden'
		| 'Sportakrobatik'
		| 'StepAerobic'
		| 'Taekwondo'
		| 'Tanzen'
		| 'Turnen'
		| 'Wandern'
		| 'Yoga';
	featuredImage: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
	};
	images?: Array<{
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
		_key: string;
	}>;
	training?: {
		trainingDescription?: SimpleBlockContent;
		trainingTimes?: Array<
			{
				_key: string;
			} & TrainingTime
		>;
	};
	isSportGroup: boolean;
};

export type SimpleBlockContent = {
	_type: 'simpleBlockContent';
	text?: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: 'span';
			_key: string;
		}>;
		style?: 'normal';
		listItem?: 'bullet' | 'number';
		markDefs?: Array<{
			href?: string;
			_type: 'link';
			_key: string;
		}>;
		level?: number;
		_type: 'block';
		_key: string;
	}>;
};

export type NewsCategory = {
	_id: string;
	_type: 'news.category';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
};

export type NewsArticle = {
	_id: string;
	_type: 'news.article';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	publishedAt: string;
	title: string;
	slug: Slug;
	categories: Array<{
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: 'news.category';
	}>;
	author: {
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: 'author';
	};
	meta?: MetaFields;
	featuredImage: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'mainImage';
	};
	excerpt: string;
	body?: Array<
		| ({
				_key: string;
		  } & BlockContent)
		| ({
				_key: string;
		  } & Blockquote)
		| ({
				_key: string;
		  } & Grid)
		| {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt: string;
				description?: string;
				_type: 'mainImage';
				_key: string;
		  }
		| ({
				_key: string;
		  } & Spacer)
	>;
};

export type MainImage = {
	_type: 'mainImage';
	asset?: {
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
	};
	media?: unknown;
	hotspot?: SanityImageHotspot;
	crop?: SanityImageCrop;
	alt: string;
	description?: string;
};

export type MetaFields = {
	_type: 'metaFields';
	metaTitle?: string;
	metaDescription?: string;
	openGraphImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	};
};

export type Author = {
	_id: string;
	_type: 'author';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	firstName: string;
	lastName: string;
	image: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
	};
	email: string;
	jobTitle: string;
};

export type ExtendedImage = {
	_type: 'extendedImage';
	asset?: {
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
	};
	media?: unknown;
	hotspot?: SanityImageHotspot;
	crop?: SanityImageCrop;
	alt: string;
	description?: string;
};

export type SanityAssistInstructionTask = {
	_type: 'sanity.assist.instructionTask';
	path?: string;
	instructionKey?: string;
	started?: string;
	updated?: string;
	info?: string;
};

export type SanityAssistTaskStatus = {
	_type: 'sanity.assist.task.status';
	tasks?: Array<
		{
			_key: string;
		} & SanityAssistInstructionTask
	>;
};

export type SanityAssistSchemaTypeAnnotations = {
	_type: 'sanity.assist.schemaType.annotations';
	title?: string;
	fields?: Array<
		{
			_key: string;
		} & SanityAssistSchemaTypeField
	>;
};

export type SanityAssistOutputType = {
	_type: 'sanity.assist.output.type';
	type?: string;
};

export type SanityAssistOutputField = {
	_type: 'sanity.assist.output.field';
	path?: string;
};

export type SanityAssistInstructionContext = {
	_type: 'sanity.assist.instruction.context';
	reference: {
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: 'assist.instruction.context';
	};
};

export type AssistInstructionContext = {
	_id: string;
	_type: 'assist.instruction.context';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	context?: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: 'span';
			_key: string;
		}>;
		style?: 'normal';
		listItem?: never;
		markDefs?: null;
		level?: number;
		_type: 'block';
		_key: string;
	}>;
};

export type SanityAssistInstructionUserInput = {
	_type: 'sanity.assist.instruction.userInput';
	message: string;
	description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
	children?: Array<
		| {
				marks?: Array<string>;
				text?: string;
				_type: 'span';
				_key: string;
		  }
		| ({
				_key: string;
		  } & SanityAssistInstructionFieldRef)
		| ({
				_key: string;
		  } & SanityAssistInstructionContext)
		| ({
				_key: string;
		  } & SanityAssistInstructionUserInput)
	>;
	style?: 'normal';
	listItem?: never;
	markDefs?: null;
	level?: number;
	_type: 'block';
	_key: string;
}>;

export type SanityAssistInstructionFieldRef = {
	_type: 'sanity.assist.instruction.fieldRef';
	path?: string;
};

export type SanityAssistInstruction = {
	_type: 'sanity.assist.instruction';
	prompt?: SanityAssistInstructionPrompt;
	icon?: string;
	title?: string;
	userId?: string;
	createdById?: string;
	output?: Array<
		| ({
				_key: string;
		  } & SanityAssistOutputField)
		| ({
				_key: string;
		  } & SanityAssistOutputType)
	>;
};

export type SanityAssistSchemaTypeField = {
	_type: 'sanity.assist.schemaType.field';
	path?: string;
	instructions?: Array<
		{
			_key: string;
		} & SanityAssistInstruction
	>;
};

export type MediaTag = {
	_id: string;
	_type: 'media.tag';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: Slug;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height: number;
	width: number;
	aspectRatio: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x: number;
	y: number;
	height: number;
	width: number;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top: number;
	bottom: number;
	left: number;
	right: number;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type Slug = {
	_type: 'slug';
	current: string;
	source?: string;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type AllSanitySchemaTypes =
	| NewsOverviewCategory
	| NewsArticlePage
	| DepartmentsPage
	| Spacer
	| Grid
	| Blockquote
	| TrainingTime
	| Stats
	| SingleGroupPage
	| Privacy
	| NewsOverview
	| Membership
	| BlockContent
	| Imprint
	| InternalLink
	| GroupsPage
	| Contact
	| AboutUs
	| Home
	| ImageCard
	| ExternalLink
	| DocumentDownload
	| ContactNameMail
	| Columns
	| SiteSettings
	| SocialFields
	| Venue
	| Testimonial
	| HonoraryMember
	| Person
	| Role
	| GroupTaekwondo
	| GroupSoccer
	| GroupOtherSports
	| GroupDance
	| GroupCourses
	| GroupChildrenGymnastics
	| GroupAdmin
	| SimpleBlockContent
	| NewsCategory
	| NewsArticle
	| MainImage
	| MetaFields
	| Author
	| ExtendedImage
	| SanityAssistInstructionTask
	| SanityAssistTaskStatus
	| SanityAssistSchemaTypeAnnotations
	| SanityAssistOutputType
	| SanityAssistOutputField
	| SanityAssistInstructionContext
	| AssistInstructionContext
	| SanityAssistInstructionUserInput
	| SanityAssistInstructionPrompt
	| SanityAssistInstructionFieldRef
	| SanityAssistInstruction
	| SanityAssistSchemaTypeField
	| MediaTag
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageHotspot
	| SanityImageCrop
	| SanityFileAsset
	| SanityImageAsset
	| SanityImageMetadata
	| Geopoint
	| Slug
	| SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/lib/sanity/queries/pages/contact.ts
// Variable: contactPageQuery
// Query: *[_type == 'contact'][0] {		...,		content {			...,			contactPersonsSection {				...,				contactPersons[]-> {					  firstName,  lastName,  phone,  image,  contactAs,  "email": affiliations[0].role->email,  "role": affiliations[0].role->title,  "taskDescription": affiliations[0].taskDescription,				}			}		}	}
export type ContactPageQueryResult = {
	_id: string;
	_type: 'contact';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	slug?: Slug;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	content: {
		receiver: Array<
			{
				_key: string;
			} & ContactNameMail
		>;
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
			contactPersons: Array<{
				firstName: string;
				lastName: string;
				phone: string | null;
				image: {
					asset?: {
						_ref: string;
						_type: 'reference';
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
					};
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt: string;
					description?: string;
					_type: 'extendedImage';
				};
				contactAs: 'both' | 'email' | 'phone' | 'whatsapp';
				email: string | null;
				role: string | null;
				taskDescription: string | null;
			}>;
		};
	};
} | null;

// Source: ./src/lib/sanity/queries/pages/home.ts
// Variable: homePageQuery
// Query: *[_type == 'home'][0] {		...,		content {			...,			contactPersonsSection {				...,				contactPersons[]-> {					  firstName,  lastName,  phone,  image,  contactAs,  "email": affiliations[0].role->email,  "role": affiliations[0].role->title,  "taskDescription": affiliations[0].taskDescription,				}			}		}	}
export type HomePageQueryResult = {
	_id: string;
	_type: 'home';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	slug?: Slug;
	title: string;
	subtitle: string;
	intro?: string;
	meta?: MetaFields;
	content: {
		featureSection: {
			title: string;
			subtitle: string;
			intro?: string;
			features?: Array<{
				title: string;
				intro: string;
				icon: string;
				_type: 'feature';
				_key: string;
			}>;
		};
		visionSection: {
			title: string;
			subtitle: string;
			intro?: string;
			cta: string;
		};
		groupsSection: {
			title: string;
			subtitle: string;
		};
		stats: Array<
			{
				_key: string;
			} & Stats
		>;
		pricingSection: {
			title: string;
			subtitle: string;
			intro?: string;
			pricingYouth: {
				title: string;
				subtitle: string;
				intro?: string;
				price: number;
				benefitsTitle: string;
				benefits: Array<string>;
				cta: string;
			};
			pricingFamily: {
				title: string;
				subtitle: string;
				intro?: string;
				price: number;
				benefitsTitle: string;
				benefits: Array<string>;
				cta: string;
			};
			pricingAdult: {
				title: string;
				subtitle: string;
				intro?: string;
				price: number;
				benefitsTitle: string;
				benefits: Array<string>;
				cta: string;
			};
		};
		testimonialSection: {
			title: string;
			subtitle: string;
			testimonials?: Array<{
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				_key: string;
				[internalGroqTypeReferenceTo]?: 'testimonial';
			}>;
		};
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
			contactPersons: Array<{
				firstName: string;
				lastName: string;
				phone: string | null;
				image: {
					asset?: {
						_ref: string;
						_type: 'reference';
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
					};
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt: string;
					description?: string;
					_type: 'extendedImage';
				};
				contactAs: 'both' | 'email' | 'phone' | 'whatsapp';
				email: string | null;
				role: string | null;
				taskDescription: string | null;
			}>;
		};
		newsSection: {
			title: string;
			subtitle: string;
			intro?: string;
		};
	};
} | null;
// Variable: homePageTestimonialsQuery
// Query: *[_type == 'home'][0].content.testimonialSection.testimonials[0..2]-> {		firstName,		lastName,		image,		quote,		role,		show,	}
export type HomePageTestimonialsQueryResult = Array<{
	firstName: string;
	lastName: string;
	image: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
	};
	quote: string;
	role: string;
	show: boolean | null;
}> | null;

// Source: ./src/lib/sanity/queries/pages/imprint.ts
// Variable: imprintPageQuery
// Query: *[_type == 'imprint'][0] {		...,		"contactForm": contactForm {			title,			"slug": link->slug.current		}	}
export type ImprintPageQueryResult = {
	_id: string;
	_type: 'imprint';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	slug?: Slug;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	intro?: SimpleBlockContent;
	address: SimpleBlockContent;
	registerCourt: string;
	registerNo: string;
	represented: SimpleBlockContent;
	email: string;
	contactForm: {
		title: string;
		slug: string | null;
	};
	responsible: string;
	consumerDisputeResolution: string;
	technicalQuestionsName: string;
	technicalQuestionsEmail: string;
	support: SimpleBlockContent;
	credits: SimpleBlockContent;
} | null;

// Source: ./src/lib/sanity/queries/pages/membership.ts
// Variable: membershipPageQuery
// Query: {		"membership": *[_type == 'membership'][0] {			...,			downloadsSection {				...,				downloads[] {					...,					document {						...,						asset->					}				}			},			contactPersonsSection {				...,				contactPersons[]-> {					  firstName,  lastName,  phone,  image,  contactAs,  "email": affiliations[0].role->email,  "role": affiliations[0].role->title,  "taskDescription": affiliations[0].taskDescription,				}			}		},		"pricingSection": *[_type == 'home'][0].content.pricingSection	}
export type MembershipPageQueryResult = {
	membership: {
		_id: string;
		_type: 'membership';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		slug?: Slug;
		title: string;
		subtitle: string;
		meta?: MetaFields;
		intro: BlockContent;
		downloadsSection: {
			title: string;
			subtitle: string;
			intro?: string;
			downloads: Array<{
				_key: string;
				_type: 'documentDownload';
				title: string;
				document: {
					asset: {
						_id: string;
						_type: 'sanity.fileAsset';
						_createdAt: string;
						_updatedAt: string;
						_rev: string;
						originalFilename?: string;
						label?: string;
						title?: string;
						description?: string;
						altText?: string;
						sha1hash?: string;
						extension?: string;
						mimeType?: string;
						size?: number;
						assetId?: string;
						uploadId?: string;
						path?: string;
						url?: string;
						source?: SanityAssetSourceData;
					} | null;
					media?: unknown;
					_type: 'file';
				};
			}>;
		};
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
			contactPersons: Array<{
				firstName: string;
				lastName: string;
				phone: string | null;
				image: {
					asset?: {
						_ref: string;
						_type: 'reference';
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
					};
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt: string;
					description?: string;
					_type: 'extendedImage';
				};
				contactAs: 'both' | 'email' | 'phone' | 'whatsapp';
				email: string | null;
				role: string | null;
				taskDescription: string | null;
			}>;
		};
	} | null;
	pricingSection: {
		title: string;
		subtitle: string;
		intro?: string;
		pricingYouth: {
			title: string;
			subtitle: string;
			intro?: string;
			price: number;
			benefitsTitle: string;
			benefits: Array<string>;
			cta: string;
		};
		pricingFamily: {
			title: string;
			subtitle: string;
			intro?: string;
			price: number;
			benefitsTitle: string;
			benefits: Array<string>;
			cta: string;
		};
		pricingAdult: {
			title: string;
			subtitle: string;
			intro?: string;
			price: number;
			benefitsTitle: string;
			benefits: Array<string>;
			cta: string;
		};
	} | null;
};

// Source: ./src/lib/sanity/queries/pages/news-article.ts
// Variable: newsArticleHeroQuery
// Query: *[_type == 'news-article-page'][0] {		title,		subtitle,	}
export type NewsArticleHeroQueryResult = {
	title: string;
	subtitle: string;
} | null;
// Variable: newsArticleContentQuery
// Query: *[_type == 'news.article' && slug.current == $slug][0] {		author -> {			email,			firstName,			image,			lastName,			jobTitle,		},		body[],		categories[] -> {			"slug": slug.current,			title		},		excerpt,		featuredImage,		publishedAt,		"slug": slug.current,		title,	}
export type NewsArticleContentQueryResult = {
	author: {
		email: string;
		firstName: string;
		image: {
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
			};
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt: string;
			description?: string;
			_type: 'extendedImage';
		};
		lastName: string;
		jobTitle: string;
	};
	body: Array<
		| ({
				_key: string;
		  } & BlockContent)
		| ({
				_key: string;
		  } & Blockquote)
		| ({
				_key: string;
		  } & Grid)
		| ({
				_key: string;
		  } & Spacer)
		| {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt: string;
				description?: string;
				_type: 'mainImage';
				_key: string;
		  }
	> | null;
	categories: Array<{
		slug: string;
		title: string;
	}>;
	excerpt: string;
	featuredImage: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'mainImage';
	};
	publishedAt: string;
	slug: string;
	title: string;
} | null;

// Source: ./src/lib/sanity/queries/pages/news-overview-category.ts
// Variable: newsOverviewCategoryPageQuery
// Query: *[_type == 'newsOverviewCategory'][0] {		...,		content {			contactPersonsSection {				...,				contactPersons[]-> {					  firstName,  lastName,  phone,  image,  contactAs,  "email": affiliations[0].role->email,  "role": affiliations[0].role->title,  "taskDescription": affiliations[0].taskDescription,				}			}		}	}
export type NewsOverviewCategoryPageQueryResult = {
	_id: string;
	_type: 'newsOverviewCategory';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	content: {
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
			contactPersons: Array<{
				firstName: string;
				lastName: string;
				phone: string | null;
				image: {
					asset?: {
						_ref: string;
						_type: 'reference';
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
					};
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt: string;
					description?: string;
					_type: 'extendedImage';
				};
				contactAs: 'both' | 'email' | 'phone' | 'whatsapp';
				email: string | null;
				role: string | null;
				taskDescription: string | null;
			}>;
		};
	};
} | null;
// Variable: newsArticlesPaginatedForCategoryQuery
// Query: *[_type == 'news.article' && $category in categories[]->slug.current]	| order(publishedAt desc) [$start..$end] {			_id,	publishedAt,	author->{ firstName, lastName, image },	categories[]->{ title, "slug": slug.current },	excerpt,	featuredImage,	"slug": slug.current,	title,	}
export type NewsArticlesPaginatedForCategoryQueryResult = Array<{
	_id: string;
	publishedAt: string;
	author: {
		firstName: string;
		lastName: string;
		image: {
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
			};
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt: string;
			description?: string;
			_type: 'extendedImage';
		};
	};
	categories: Array<{
		title: string;
		slug: string;
	}>;
	excerpt: string;
	featuredImage: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'mainImage';
	};
	slug: string;
	title: string;
}>;
// Variable: newsArticlesTotalForCategoryQuery
// Query: count(*[_type == "news.article" && $category in categories[]->slug.current])
export type NewsArticlesTotalForCategoryQueryResult = number;

// Source: ./src/lib/sanity/queries/pages/news-overview.ts
// Variable: newsOverviewPageQuery
// Query: *[_type == 'newsOverview'][0] {		...,		content {			contactPersonsSection {				...,				contactPersons[]-> {					  firstName,  lastName,  phone,  image,  contactAs,  "email": affiliations[0].role->email,  "role": affiliations[0].role->title,  "taskDescription": affiliations[0].taskDescription,				}			}		}	}
export type NewsOverviewPageQueryResult = {
	_id: string;
	_type: 'newsOverview';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	slug?: Slug;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	content: {
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
			contactPersons: Array<{
				firstName: string;
				lastName: string;
				phone: string | null;
				image: {
					asset?: {
						_ref: string;
						_type: 'reference';
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
					};
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt: string;
					description?: string;
					_type: 'extendedImage';
				};
				contactAs: 'both' | 'email' | 'phone' | 'whatsapp';
				email: string | null;
				role: string | null;
				taskDescription: string | null;
			}>;
		};
	};
} | null;

// Source: ./src/lib/sanity/queries/pages/offer-groups-group.ts
// Variable: offerGroupsGroupPageQuery
// Query: *[_type == 'singleGroupPage'][0]
export type OfferGroupsGroupPageQueryResult = {
	_id: string;
	_type: 'singleGroupPage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	content: {
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
		};
		trainingSection: {
			title: string;
		};
	};
} | null;
// Variable: offerGroupsGroupPageGroupsQuery
// Query: *[_type == $groupType && slug.current == $slug][0] {		description,		featuredImage,		images,		title,		training {			trainingDescription,			trainingTimes[] {				...,				venue->			}		}	}
export type OfferGroupsGroupPageGroupsQueryResult =
	| {
			description: SimpleBlockContent;
			featuredImage: null;
			images: null;
			title: string;
			training: null;
	  }
	| {
			description: SimpleBlockContent;
			featuredImage: {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt: string;
				description?: string;
				_type: 'extendedImage';
			};
			images: Array<{
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt: string;
				description?: string;
				_type: 'extendedImage';
				_key: string;
			}> | null;
			title: string;
			training: {
				trainingDescription: SimpleBlockContent | null;
				trainingTimes: Array<{
					_key: string;
					_type: 'trainingTime';
					season: 'summer' | 'winter' | 'yearly';
					weekday:
						| 'friday'
						| 'monday'
						| 'saturday'
						| 'sunday'
						| 'thursday'
						| 'tuesday'
						| 'wednesday';
					startTime: string;
					endTime: string;
					venue: {
						_id: string;
						_type: 'venue';
						_createdAt: string;
						_updatedAt: string;
						_rev: string;
						title: string;
						description: SimpleBlockContent;
						type:
							| 'artificial-turf'
							| 'cinder'
							| 'grass'
							| 'hall-1'
							| 'hall-2'
							| 'hall-3'
							| 'hybrid';
						mainImage?: {
							asset?: {
								_ref: string;
								_type: 'reference';
								_weak?: boolean;
								[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
							};
							media?: unknown;
							hotspot?: SanityImageHotspot;
							crop?: SanityImageCrop;
							alt: string;
							description?: string;
							_type: 'image';
						};
						location?: {
							name: string;
							street: string;
							houseNumber: string;
							zipCode?: string;
							city: string;
						};
					};
					note?: string;
				}> | null;
			};
	  }
	| {
			description: SimpleBlockContent;
			featuredImage: {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt: string;
				description?: string;
				_type: 'extendedImage';
			};
			images: Array<{
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt: string;
				description?: string;
				_type: 'extendedImage';
				_key: string;
			}> | null;
			title: string;
			training: {
				trainingDescription: SimpleBlockContent | null;
				trainingTimes: Array<{
					_key: string;
					_type: 'trainingTime';
					season: 'summer' | 'winter' | 'yearly';
					weekday:
						| 'friday'
						| 'monday'
						| 'saturday'
						| 'sunday'
						| 'thursday'
						| 'tuesday'
						| 'wednesday';
					startTime: string;
					endTime: string;
					venue: {
						_id: string;
						_type: 'venue';
						_createdAt: string;
						_updatedAt: string;
						_rev: string;
						title: string;
						description: SimpleBlockContent;
						type:
							| 'artificial-turf'
							| 'cinder'
							| 'grass'
							| 'hall-1'
							| 'hall-2'
							| 'hall-3'
							| 'hybrid';
						mainImage?: {
							asset?: {
								_ref: string;
								_type: 'reference';
								_weak?: boolean;
								[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
							};
							media?: unknown;
							hotspot?: SanityImageHotspot;
							crop?: SanityImageCrop;
							alt: string;
							description?: string;
							_type: 'image';
						};
						location?: {
							name: string;
							street: string;
							houseNumber: string;
							zipCode?: string;
							city: string;
						};
					};
					note?: string;
				}> | null;
			} | null;
	  }
	| {
			description: null;
			featuredImage: null;
			images: null;
			title: null;
			training: null;
	  }
	| {
			description: null;
			featuredImage: null;
			images: null;
			title: string;
			training: null;
	  }
	| {
			description: null;
			featuredImage: null;
			images: null;
			title: string | null;
			training: null;
	  }
	| {
			description: null;
			featuredImage: {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt: string;
				description?: string;
				_type: 'mainImage';
			};
			images: null;
			title: string;
			training: null;
	  }
	| {
			description: string | null;
			featuredImage: null;
			images: null;
			title: string | null;
			training: null;
	  }
	| null;
// Variable: offerGroupsGroupPageContactPersonsQuery
// Query: *[		_type == 'person' &&		defined(affiliations[team->slug.current == $slug][0])	]|order(lastName asc) {		_id,		firstName,		lastName,		phone,		image,		contactAs,		"email": affiliations[team->slug.current == $slug][0].team->email,		"role":  affiliations[team->slug.current == $slug][0].role->title,		"team":  affiliations[team->slug.current == $slug][0].team->title,		"taskDescription": affiliations[team->slug.current == $slug][0].taskDescription,	}
export type OfferGroupsGroupPageContactPersonsQueryResult = Array<{
	_id: string;
	firstName: string;
	lastName: string;
	phone: string | null;
	image: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
	};
	contactAs: 'both' | 'email' | 'phone' | 'whatsapp';
	email: string | null;
	role: string | null;
	team: string | null;
	taskDescription: string | null;
}>;

// Source: ./src/lib/sanity/queries/pages/offer-groups.ts
// Variable: offerGroupsPageQuery
// Query: *[_type == 'groupsPage'][0]
export type OfferGroupsPageQueryResult = {
	_id: string;
	_type: 'groupsPage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	content: {
		groupsSection: {
			title: string;
			subtitle: string;
			intro?: string;
		};
		stats: Array<
			{
				_key: string;
			} & Stats
		>;
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
		};
	};
} | null;
// Variable: offerGroupsPageGroupsQuery
// Query: *[_type == $groupType][] | order(sortOrder asc) {		icon,		featuredImage,		overviewTitle,		'slug': slug.current,		title,	}
export type OfferGroupsPageGroupsQueryResult = Array<
	| {
			icon: null;
			featuredImage: null;
			overviewTitle: null;
			slug: null;
			title: null;
	  }
	| {
			icon: null;
			featuredImage: null;
			overviewTitle: null;
			slug: null;
			title: string;
	  }
	| {
			icon: null;
			featuredImage: null;
			overviewTitle: null;
			slug: null;
			title: string | null;
	  }
	| {
			icon: null;
			featuredImage: null;
			overviewTitle: null;
			slug: string;
			title: string;
	  }
	| {
			icon: null;
			featuredImage: null;
			overviewTitle: null;
			slug: string | null;
			title: string;
	  }
	| {
			icon:
				| 'Badminton'
				| 'Bodenturnen'
				| 'Cheerleading'
				| 'Fitness'
				| 'Fussball'
				| 'Gymnastik'
				| 'Jujutsu'
				| 'Pilates'
				| 'RopeSkipping'
				| 'Sportakrobatik'
				| 'SportInGebaeuden'
				| 'StepAerobic'
				| 'Taekwondo'
				| 'Tanzen'
				| 'Turnen'
				| 'Wandern'
				| 'Yoga';
			featuredImage: {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt: string;
				description?: string;
				_type: 'extendedImage';
			};
			overviewTitle: string | null;
			slug: string;
			title: string;
	  }
	| {
			icon: null;
			featuredImage: {
				asset?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt: string;
				description?: string;
				_type: 'mainImage';
			};
			overviewTitle: null;
			slug: string;
			title: string;
	  }
>;
// Variable: offerGroupsPageContactPersonsQuery
// Query: *[_type == 'person'][affiliations[0].role->email == $email] {		  firstName,  lastName,  phone,  image,  contactAs,  "email": affiliations[0].role->email,  "role": affiliations[0].role->title,  "taskDescription": affiliations[0].taskDescription,	}
export type OfferGroupsPageContactPersonsQueryResult = Array<{
	firstName: string;
	lastName: string;
	phone: string | null;
	image: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'extendedImage';
	};
	contactAs: 'both' | 'email' | 'phone' | 'whatsapp';
	email: string | null;
	role: string | null;
	taskDescription: string | null;
}>;

// Source: ./src/lib/sanity/queries/pages/offer.ts
// Variable: offerPageQuery
// Query: *[_type == 'departmentsPage'][0] {	...,	content {		...,		contactPersonsSection {			...,			contactPersons[]-> {				  firstName,  lastName,  phone,  image,  contactAs,  "email": affiliations[0].role->email,  "role": affiliations[0].role->title,  "taskDescription": affiliations[0].taskDescription,			}		}	}}
export type OfferPageQueryResult = {
	_id: string;
	_type: 'departmentsPage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	slug?: Slug;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	content: {
		departmentsSection: {
			title: string;
			subtitle: string;
			intro?: string;
		};
		stats: Array<
			{
				_key: string;
			} & Stats
		>;
		contactPersonsSection: {
			title: string;
			subtitle: string;
			intro?: string;
			contactPersons: Array<{
				firstName: string;
				lastName: string;
				phone: string | null;
				image: {
					asset?: {
						_ref: string;
						_type: 'reference';
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
					};
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt: string;
					description?: string;
					_type: 'extendedImage';
				};
				contactAs: 'both' | 'email' | 'phone' | 'whatsapp';
				email: string | null;
				role: string | null;
				taskDescription: string | null;
			}>;
		};
	};
} | null;

// Source: ./src/lib/sanity/queries/pages/privacy.ts
// Variable: privacyPageQuery
// Query: *[_type == 'privacy'][0]
export type PrivacyPageQueryResult = {
	_id: string;
	_type: 'privacy';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	slug?: Slug;
	title: string;
	subtitle: string;
	meta?: MetaFields;
	introText: BlockContent;
	address: string;
	phone?: string;
	email: string;
	content: BlockContent;
} | null;

// Source: ./src/lib/sanity/queries/shared/groups.ts
// Variable: groupsQuery
// Query: *[_type in [		'group.soccer',		'group.children-gymnastics',		'group.courses',		'group.taekwondo',		'group.dance',		'group.other-sports',	]] {		_id,		title,		icon,	}
export type GroupsQueryResult = Array<{
	_id: string;
	title: string;
	icon:
		| 'Badminton'
		| 'Bodenturnen'
		| 'Cheerleading'
		| 'Fitness'
		| 'Fussball'
		| 'Gymnastik'
		| 'Jujutsu'
		| 'Pilates'
		| 'RopeSkipping'
		| 'Sportakrobatik'
		| 'SportInGebaeuden'
		| 'StepAerobic'
		| 'Taekwondo'
		| 'Tanzen'
		| 'Turnen'
		| 'Wandern'
		| 'Yoga';
}>;

// Source: ./src/lib/sanity/queries/shared/news.ts
// Variable: newsArticlesQuery
// Query: *[_type == 'news.article'] | order(publishedAt desc) [0..2] {			_id,	publishedAt,	author->{ firstName, lastName, image },	categories[]->{ title, "slug": slug.current },	excerpt,	featuredImage,	"slug": slug.current,	title,	}
export type NewsArticlesQueryResult = Array<{
	_id: string;
	publishedAt: string;
	author: {
		firstName: string;
		lastName: string;
		image: {
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
			};
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt: string;
			description?: string;
			_type: 'extendedImage';
		};
	};
	categories: Array<{
		title: string;
		slug: string;
	}>;
	excerpt: string;
	featuredImage: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'mainImage';
	};
	slug: string;
	title: string;
}>;
// Variable: newsArticlesPaginatedQuery
// Query: *[_type == 'news.article'] | order(publishedAt desc) [$start..$end] { // $start = 3, $end = 8			_id,	publishedAt,	author->{ firstName, lastName, image },	categories[]->{ title, "slug": slug.current },	excerpt,	featuredImage,	"slug": slug.current,	title,	}
export type NewsArticlesPaginatedQueryResult = Array<{
	_id: string;
	publishedAt: string;
	author: {
		firstName: string;
		lastName: string;
		image: {
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
			};
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt: string;
			description?: string;
			_type: 'extendedImage';
		};
	};
	categories: Array<{
		title: string;
		slug: string;
	}>;
	excerpt: string;
	featuredImage: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt: string;
		description?: string;
		_type: 'mainImage';
	};
	slug: string;
	title: string;
}>;
// Variable: newsArticlesTotalQuery
// Query: count(*[_type == "news.article"])
export type NewsArticlesTotalQueryResult = number;
// Variable: newsCategoryQuery
// Query: *[_type == 'news.category' && slug.current == $slug][0] {		"slug": slug.current,		title	}
export type NewsCategoryQueryResult = {
	slug: string;
	title: string;
} | null;

// Source: ./src/lib/sanity/queries/shared/social-media.ts
// Variable: socialMediaQuery
// Query: *[_type == 'site-settings'][0].socialFields
export type SocialMediaQueryResult = SocialFields | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
	interface SanityQueries {
		'\n\t*[_type == \'contact\'][0] {\n\t\t...,\n\t\tcontent {\n\t\t\t...,\n\t\t\tcontactPersonsSection {\n\t\t\t\t...,\n\t\t\t\tcontactPersons[]-> {\n\t\t\t\t\t\n  firstName,\n  lastName,\n  phone,\n  image,\n  contactAs,\n  "email": affiliations[0].role->email,\n  "role": affiliations[0].role->title,\n  "taskDescription": affiliations[0].taskDescription,\n\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n': ContactPageQueryResult;
		'\n\t*[_type == \'home\'][0] {\n\t\t...,\n\t\tcontent {\n\t\t\t...,\n\t\t\tcontactPersonsSection {\n\t\t\t\t...,\n\t\t\t\tcontactPersons[]-> {\n\t\t\t\t\t\n  firstName,\n  lastName,\n  phone,\n  image,\n  contactAs,\n  "email": affiliations[0].role->email,\n  "role": affiliations[0].role->title,\n  "taskDescription": affiliations[0].taskDescription,\n\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n': HomePageQueryResult;
		"\n\t*[_type == 'home'][0].content.testimonialSection.testimonials[0..2]-> {\n\t\tfirstName,\n\t\tlastName,\n\t\timage,\n\t\tquote,\n\t\trole,\n\t\tshow,\n\t}\n": HomePageTestimonialsQueryResult;
		'\n\t*[_type == \'imprint\'][0] {\n\t\t...,\n\t\t"contactForm": contactForm {\n\t\t\ttitle,\n\t\t\t"slug": link->slug.current\n\t\t}\n\t}\n': ImprintPageQueryResult;
		'\n\t{\n\t\t"membership": *[_type == \'membership\'][0] {\n\t\t\t...,\n\t\t\tdownloadsSection {\n\t\t\t\t...,\n\t\t\t\tdownloads[] {\n\t\t\t\t\t...,\n\t\t\t\t\tdocument {\n\t\t\t\t\t\t...,\n\t\t\t\t\t\tasset->\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t},\n\t\t\tcontactPersonsSection {\n\t\t\t\t...,\n\t\t\t\tcontactPersons[]-> {\n\t\t\t\t\t\n  firstName,\n  lastName,\n  phone,\n  image,\n  contactAs,\n  "email": affiliations[0].role->email,\n  "role": affiliations[0].role->title,\n  "taskDescription": affiliations[0].taskDescription,\n\n\t\t\t\t}\n\t\t\t}\n\t\t},\n\t\t"pricingSection": *[_type == \'home\'][0].content.pricingSection\n\t}\n': MembershipPageQueryResult;
		"\n\t*[_type == 'news-article-page'][0] {\n\t\ttitle,\n\t\tsubtitle,\n\t}\n": NewsArticleHeroQueryResult;
		'\n\t*[_type == \'news.article\' && slug.current == $slug][0] {\n\t\tauthor -> {\n\t\t\temail,\n\t\t\tfirstName,\n\t\t\timage,\n\t\t\tlastName,\n\t\t\tjobTitle,\n\t\t},\n\t\tbody[],\n\t\tcategories[] -> {\n\t\t\t"slug": slug.current,\n\t\t\ttitle\n\t\t},\n\t\texcerpt,\n\t\tfeaturedImage,\n\t\tpublishedAt,\n\t\t"slug": slug.current,\n\t\ttitle,\n\t}\n': NewsArticleContentQueryResult;
		'\n\t*[_type == \'newsOverviewCategory\'][0] {\n\t\t...,\n\t\tcontent {\n\t\t\tcontactPersonsSection {\n\t\t\t\t...,\n\t\t\t\tcontactPersons[]-> {\n\t\t\t\t\t\n  firstName,\n  lastName,\n  phone,\n  image,\n  contactAs,\n  "email": affiliations[0].role->email,\n  "role": affiliations[0].role->title,\n  "taskDescription": affiliations[0].taskDescription,\n\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n': NewsOverviewCategoryPageQueryResult;
		'\n\t*[_type == \'news.article\' && $category in categories[]->slug.current]\n\t| order(publishedAt desc) [$start..$end] {\n\t\t\n\t_id,\n\tpublishedAt,\n\tauthor->{ firstName, lastName, image },\n\tcategories[]->{ title, "slug": slug.current },\n\texcerpt,\n\tfeaturedImage,\n\t"slug": slug.current,\n\ttitle,\n\n\t}\n': NewsArticlesPaginatedForCategoryQueryResult;
		'\n\tcount(*[_type == "news.article" && $category in categories[]->slug.current])\n': NewsArticlesTotalForCategoryQueryResult;
		'\n\t*[_type == \'newsOverview\'][0] {\n\t\t...,\n\t\tcontent {\n\t\t\tcontactPersonsSection {\n\t\t\t\t...,\n\t\t\t\tcontactPersons[]-> {\n\t\t\t\t\t\n  firstName,\n  lastName,\n  phone,\n  image,\n  contactAs,\n  "email": affiliations[0].role->email,\n  "role": affiliations[0].role->title,\n  "taskDescription": affiliations[0].taskDescription,\n\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n': NewsOverviewPageQueryResult;
		"*[_type == 'singleGroupPage'][0]": OfferGroupsGroupPageQueryResult;
		'\n\t*[_type == $groupType && slug.current == $slug][0] {\n\t\tdescription,\n\t\tfeaturedImage,\n\t\timages,\n\t\ttitle,\n\t\ttraining {\n\t\t\ttrainingDescription,\n\t\t\ttrainingTimes[] {\n\t\t\t\t...,\n\t\t\t\tvenue->\n\t\t\t}\n\t\t}\n\t}\n': OfferGroupsGroupPageGroupsQueryResult;
		'\n\t*[\n\t\t_type == \'person\' &&\n\t\tdefined(affiliations[team->slug.current == $slug][0])\n\t]|order(lastName asc) {\n\t\t_id,\n\t\tfirstName,\n\t\tlastName,\n\t\tphone,\n\t\timage,\n\t\tcontactAs,\n\t\t"email": affiliations[team->slug.current == $slug][0].team->email,\n\t\t"role":  affiliations[team->slug.current == $slug][0].role->title,\n\t\t"team":  affiliations[team->slug.current == $slug][0].team->title,\n\t\t"taskDescription": affiliations[team->slug.current == $slug][0].taskDescription,\n\t}\n': OfferGroupsGroupPageContactPersonsQueryResult;
		"*[_type == 'groupsPage'][0]": OfferGroupsPageQueryResult;
		"\n\t*[_type == $groupType][] | order(sortOrder asc) {\n\t\ticon,\n\t\tfeaturedImage,\n\t\toverviewTitle,\n\t\t'slug': slug.current,\n\t\ttitle,\n\t}\n": OfferGroupsPageGroupsQueryResult;
		'\n\t*[_type == \'person\'][affiliations[0].role->email == $email] {\n\t\t\n  firstName,\n  lastName,\n  phone,\n  image,\n  contactAs,\n  "email": affiliations[0].role->email,\n  "role": affiliations[0].role->title,\n  "taskDescription": affiliations[0].taskDescription,\n\n\t}\n': OfferGroupsPageContactPersonsQueryResult;
		'\n*[_type == \'departmentsPage\'][0] {\n\t...,\n\tcontent {\n\t\t...,\n\t\tcontactPersonsSection {\n\t\t\t...,\n\t\t\tcontactPersons[]-> {\n\t\t\t\t\n  firstName,\n  lastName,\n  phone,\n  image,\n  contactAs,\n  "email": affiliations[0].role->email,\n  "role": affiliations[0].role->title,\n  "taskDescription": affiliations[0].taskDescription,\n\n\t\t\t}\n\t\t}\n\t}\n}\n': OfferPageQueryResult;
		"*[_type == 'privacy'][0]": PrivacyPageQueryResult;
		"\n\t*[_type in [\n\t\t'group.soccer',\n\t\t'group.children-gymnastics',\n\t\t'group.courses',\n\t\t'group.taekwondo',\n\t\t'group.dance',\n\t\t'group.other-sports',\n\t]] {\n\t\t_id,\n\t\ttitle,\n\t\ticon,\n\t}\n": GroupsQueryResult;
		'\n\t*[_type == \'news.article\'] | order(publishedAt desc) [0..2] {\n\t\t\n\t_id,\n\tpublishedAt,\n\tauthor->{ firstName, lastName, image },\n\tcategories[]->{ title, "slug": slug.current },\n\texcerpt,\n\tfeaturedImage,\n\t"slug": slug.current,\n\ttitle,\n\n\t}\n': NewsArticlesQueryResult;
		'\n\t*[_type == \'news.article\'] | order(publishedAt desc) [$start..$end] { // $start = 3, $end = 8\n\t\t\n\t_id,\n\tpublishedAt,\n\tauthor->{ firstName, lastName, image },\n\tcategories[]->{ title, "slug": slug.current },\n\texcerpt,\n\tfeaturedImage,\n\t"slug": slug.current,\n\ttitle,\n\n\t}\n': NewsArticlesPaginatedQueryResult;
		'count(*[_type == "news.article"])': NewsArticlesTotalQueryResult;
		'\n\t*[_type == \'news.category\' && slug.current == $slug][0] {\n\t\t"slug": slug.current,\n\t\ttitle\n\t}\n': NewsCategoryQueryResult;
		"*[_type == 'site-settings'][0].socialFields": SocialMediaQueryResult;
	}
}
