name: SonarCloud

on:
  push:
    branches:
      - main
      - next
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          cache: pnpm
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Collect Coverage
        run: pnpm run test:coverage
        env:
          NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 # v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
